language: php
install:
  - composer install --no-interaction
matrix:
  fast_finish: true
  allow_failures:
    - php: "7.4"
php:
  - "7.3"
  - "7.4"
script:
  - mkdir -p coverage
  - composer test
after_success:
  - composer clover
  - travis_retry php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage/clover.xml
