name: Run PHPSpec tests
on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
            - 'doc/**'
jobs:
    run:
        name: PHP ${{ matrix.php-versions }} Spec on ${{ matrix.operating-system }}
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-20.04, ubuntu-18.04, windows-latest, macos-latest]
                php-versions: ['8.0', '8.1']
        env:
            extensions: mbstring, pdo, pdo_mysql, spl
            key: cache-v1
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup cache environment
              id: cache-env
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ${{ env.extensions }}
                  key: ${{ env.key }}

            - name: Cache extensions
              uses: actions/cache@v2
              with:
                  path: ${{ steps.cache-env.outputs.dir }}
                  key: ${{ steps.cache-env.outputs.key }}
                  restore-keys: ${{ steps.cache-env.outputs.key }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ${{ env.extensions }}

            - name: Testing PHP version
              run: |
                  php -v
                  php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"
            - name: Testing Composer version
              run: |
                  composer -V
                  php -r "if(strpos(@exec('composer -V'), 'Composer version') === false) {throw new Exception('Composer not found');}"
            - name: Testing Extensions
              run: |
                  php -m
                  php -r "if(! extension_loaded('mbstring')) {throw new Exception('mbstring not found');}"
                  php -r "if(! extension_loaded('pdo')) {throw new Exception('pdo not found');}"
                  php -r "if(! extension_loaded('pdo_mysql')) {throw new Exception('pdo_mysql not found');}"
                  php -r "if(! extension_loaded('spl')) {throw new Exception('spl not found');}"
#            - name: Testing ini values
#              run: |
#                  php -r "if(ini_get('memory_limit')!='-1') {throw new Exception('memory_limit not disabled');}"
#                  php -r "if(ini_get('post_max_size')!='256M') {throw new Exception('post_max_size not added');}"
#                  php -r "if(ini_get('short_open_tag')!=1) {throw new Exception('short_open_tag not added');}"
#                  php -r "if(ini_get('date.timezone')!='Asia/Kolkata') {throw new Exception('date.timezone not added');}"
            - name: Run PHPSpec
              run: composer test
